#!/usr/bin/env python3

import os
import sys
import unittest

this_dir = os.path.dirname(os.path.abspath(__file__))
os.chdir(this_dir)
os.environ['RIGSDB'] = os.path.join(this_dir, 'rigs')
src_dir = os.path.join(this_dir, 'src')

sys.path.insert(0, src_dir)

suite = unittest.defaultTestLoader.discover('test')
runner = unittest.TextTestRunner()
runner.run(suite)
