from enum import auto, IntFlag


class Level(IntFlag):
    PREAMP = auto()
    ATT = auto()
    VOXDELAY = auto()
    AF = auto()
    RF = auto()
    SQL = auto()
    IF = auto()
    APF = auto()
    NR = auto()
    PBT_IN = auto()
    PBT_OUT = auto()
    CWPITCH = auto()
    RFPOWER = auto()
    MICGAIN = auto()
    KEYSPD = auto()
    NOTCHF = auto()
    COMP = auto()
    AGC = auto()
    BKINDL = auto()
    BALANCE = auto()
    METER = auto()
    VOXGAIN = auto()
    ANTIVOX = auto()
    SLOPE_LOW = auto()
    SLOPE_HIGH = auto()
    BKIN_DLYMS = auto()
    RAWSTR = auto()
    SQLSTAT = auto()
    SWR = auto()
    ALC = auto()
    STRENGTH = auto()
    EL_BWC = auto()
    RFPOWER_METER = auto()
    COMP_METER = auto()
    VD_METER = auto()
    ID_METER = auto()
    NOTCHF_RAW = auto()
    MONITOR_GAIN = auto()
    NB = auto()

    def __str__(self):
        return self.name
