#!/usr/bin/env python3

from radioctl.icom import IcomXcvr
from radioctl.server import Server
from radioctl.utils import logging
from radioctl.ic910 import IC910

import argparse
import asyncio

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    args = parser.parse_args()
 
    logging.getLogger('default').setLevel(logging.LogLevel.DEBUG)
    #server = Server()
    #loop = asyncio.get_event_loop()
    #loop.create_task(server.start())
    #loop.run_forever()
    #ic = IcomXcvr('/dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0', 19200)
    #loop.create_task(ic.open())
    #loop.create_task(ic.writecmd(0x00))
    #loop.run_forever()
    print(IC910.capabilities(1).format_for_rigctl())
